name: Aggiorna dati predazioni

on:
  schedule:
    - cron: '0 18 * * *'  # Ogni giorno alle 18:00
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser psycopg2

      - name: Esegui script di aggiornamento
        env:
          POSTGIS_DBNAME: ${{ secrets.POSTGIS_DBNAME }}
          POSTGIS_USER: ${{ secrets.POSTGIS_USER }}
          POSTGIS_PASSWORD: ${{ secrets.POSTGIS_PASSWORD }}
          POSTGIS_HOST: ${{ secrets.POSTGIS_HOST }}
          POSTGIS_PORT: ${{ secrets.POSTGIS_PORT }}
        run: python import_feed.py
